{% set name = "anyio" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: e1875bb4b4e2de1669f4bc7869b6d3f54231cdced71605e6e64c9be77e3be50f
  - folder: src
    url: https://github.com/agronholm/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 64e2b1158ace6fee6c990ab78ee79707c0dea3f7f833a9541cd6ad056802ff87

build:
  number: 0
  # trigger: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [py<36]

requirements:
  build:
    - m2-patch                               # [win]
    - patch                                  # [not win]
  host:
    - pip
    - python
    - setuptools-scm >=3.4
    - setuptools >=42
    - toml
    - wheel >=0.29.0
  run:
    - contextvars  # [py<37]
    - dataclasses  # [py<37]
    - idna >=2.8
    - python >=3.6.2
    - sniffio >=1.1
    - typing_extensions  # [py<38]
  run_constrained:
    - trio >=0.16

test:
  source_files:
    - src/tests
  requires:
    - contextlib2  # [py<37]
    - coverage >=4.5
    - trio
    - hypothesis >=4.0
    - mock >=4
    - pip
    - pytest >=6.0
    - pytest-cov
    - pytest-mock >=3.6.1
    - toml
    - trustme
    # won't be available on pypy, or windows, any time soon
    - uvloop  # [unix and python_impl == 'cpython']
    - ruamel_yaml  # [win]
  imports:
    - anyio
  commands:
    - pip check || 1     # [win]
    - pip check || true  # [unix]
  # To check if downstream packages run without errors
  downstreams:
    # Testing jupyter_server sometimes fails in win platforms
    - jupyter_server  # [unix]

about:
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  dev_url: https://github.com/agronholm/anyio
  doc_url: https://anyio.readthedocs.io
  doc_source_url: https://github.com/agronholm/anyio/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
