{% set name = "anyio" %}
{% set version = "4.15.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f28306018cbd6d329e64a36d58256edff76dd996fe423bc957326e578b82a94
  patches:
    # edit/remove in case if of value changed/fixed  https://github.com/agronholm/anyio/blob/ffcd1542cd6d127980205f90a0100078849dd703/pyproject.toml#L137 
    - patches/fix_pytest_timeout_fromat_toml.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools-scm >=6.4
    - setuptools >=77
  run:
    - python
    - exceptiongroup >=1.0.2  # [py<311]
    - idna >=2.8
    - typing_extensions >=4.16.0  # [py<315]
  run_constrained:
    - trio >=0.32.0 

# E   subprocess.CalledProcessError
{% set deselect_tests = " --deselect=tests/test_lazyimport.py::test_sourceless_install" %}

test:
  source_files:
    - tests
    - pyproject.toml
    - src
  requires:
    - hypothesis >=4.18.2
    - pip
    - psutil >=5.9
    - pytest >=9.0
    - pytest-mock >=3.14
    - pytest-timeout
    - trustme >= 1.0.0
    - truststore >= 0.9.1
    - uvloop >=0.22.1  # [unix]
    - trio
  imports:
    - anyio
  commands:
    - pip check
    - pytest -v -m "not network" {{ deselect_tests }} tests

about:
  home: https://github.com/agronholm/anyio
  description: |
    AnyIO is an asynchronous networking and concurrency library that works on top of
    either asyncio or trio. It implements trio-like structured concurrency (SC) on top of
    asyncio and works in harmony with the native SC of trio itself.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  dev_url: https://github.com/agronholm/anyio
  doc_url: https://anyio.readthedocs.io

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
