{% set name = "anyio" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35075abd32cf20fd7e0be2fee3614e80b92d5392eba257c8d2f33de3df7ca237

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.2
    - setuptools_scm
  run:
    - async_generator  # [py<37]
    - dataclasses  # [py<37]
    - idna >=2.8
    - python >=3.6.2
    - sniffio >=1.1
    - typing_extensions # [py<38]
  run_constrained:
    - trio >=0.16
    - curio >=1.4

test:
  requires:
    - pip
  imports:
    - anyio
  commands:
    - pip check

about:
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python

extra:
  recipe-maintainers:
    - CJ-Wright
