travis:
  secure:
    BINSTAR_TOKEN: j3AgSAI4OXxeVHVJvL6aUn6K2aqnvi6ztUQgQmxIMMRvDpOeoNG9GwUJlOArXllFJiTphdTPMcAt9BkOrhQ5R7SIPk35X9gk7KIDwKqWINQhLc2+3p8EnYgVX6TdoSrfowUomIhwLXB51CDl+L0j0Y4HTrLE4YFYF5KNiHf9Q/IFNLt22HcebXrrXkWbmg23p9w5CB0sQQzlNHEGM7LLFQBlMlBjvWVZf0MGnGdU/4N+cKJyIrqA9qjhN0K/7m+mDBdZkHKARI0kTM1FzMfYJ1SfG2W/ZnYCcDG8va0TucxIwY0Q0AIgb1GW3jDcN9YQyve8LljXbXuzEC3CLHAN7cPfNgZln9pFb3W/bIq9nBjRSSdtsmz6CUxaDH4M5KGITIUiIq+LLGjIcT1WxViFAgaYC7Xjq6ehwBUsKKHQgN8xlbly/VzMdOGELBedRn1Kjnr/ue4wZWPaeQNYT4Ek1MCVHaMtgDLFp4W+cOyHsIDLuZGwHAwfuTF3R8mtyfCl9wkFfy1PyEHyvFaFdGcpDt8fBBlcN1jboxJRtEqbFcVSjKeZbIrQWwHyk8ajEEoZ5B3krq05LtFtY3ZpqyddQYNRbKH7bwAsJerEzu5BpRAH7X7Qdqz4H0pzukdxBqDORoird7PPkAnXSVjuJ4AHr3ynyAvnwzK+XsTKW8qUkRk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
